### ISSUE TITLE
Bug found in Appointment Class

### ISSUE THREAD

**Issue by dfordarius** [AY2223S2-CS2103T-T15-2/tp#90]
Maybe would be better if we use Java's LocalDate API to check the validity of the appointment date. 

Bugs that are potential with our current string regex validation: 

Users are able to enter the appointment date: "29-02-2021" in the correct (dd-MM-yyyy) format but 2021 is not a leap year.

**Comment by jundatan** [comment]
Jia hui will be adding improvements on the Appointment class. @OliviaJHL Take note.
